### ISSUE TITLE
Messaging API's

### ISSUE THREAD

**Issue by Redth** [xamarin/Caboodle#10]
Issues moved to #25 (phone dialler), #26 (sms), #27 (email)

**Comment by mattleibow** [comment]
Should these maybe be separate issues? Or are they all going to be in the same class? I think separate and small makes things easier: PhoneDialer, Sms, Email

**Comment by jamesmontemagno** [comment]
Agreed!

**Comment by Redth** [comment]
Not all the same class. We don't have to make an issue per class in general but we can split these ones out.

**Comment by mattleibow** [comment]
PhoneDialler API's moved to #25.

**Comment by mattleibow** [comment]
SMS API's moved to https://github.com/xamarin/Caboodle/issues/26.

**Comment by mattleibow** [comment]
Closing this issue as each API now has it's own issue.
