### ISSUE TITLE
Clipboard API's

### ISSUE THREAD

**Issue by Redth** [xamarin/Caboodle#11]
Clipboard manipulation:

```csharp 
class Clipboard {
    void SetText(string text);
    void SetText(string text, string label);
    bool HasText { get; }
    Task<string> GetTextAsync();
}
```

 - UWP: https://docs.microsoft.com/en-us/windows/uwp/app-to-app/copy-and-paste
 - Android: https://developer.android.com/reference/android/content/ClipboardManager.html
 - iOS https://developer.apple.com/documentation/uikit/uipasteboard

**Comment by Redth** [comment]
This needs API's drafted for sharing text content...

**Comment by jamesmontemagno** [comment]
I changed to just clipboard :)

So SetText is easy, we should have a GetText.

Should analyze if they need to be async or not....

**Comment by mattleibow** [comment]
@jamesmontemagno I had a look, and it doesn't appear to need async. Also, it doesn't matter since a copy/cut operation is fire-and-forget - there is no reason to get the app to wait until the clipboard accepts the text.

**Comment by jamesmontemagno** [comment]
I think maybe get text on uwp may need async... ?

**Comment by mattleibow** [comment]
Hmm. Appears so. The get on UWP is async, iOS and Android are not.

**Comment by mattleibow** [comment]
I suppose we can have a `bool SetText()` and a `Task<bool> GetTextAsync()`...

**Comment by mattleibow** [comment]
Also, iOS and UWP support copying images to the clipboard, do we want to do that?

**Comment by Redth** [comment]
Images add a whole level of complexity which we do not need for v1. Also not sure how many people would realistically use it. Let's leave it out for now.

Also why bool return types? Let us throw an exception if something fails, not return false. 

GetTextAsync should be Task<string>.

**Comment by jamesmontemagno** [comment]
I like the idea of exceptions in general for it.

**Comment by jamesmontemagno** [comment]
Also agree images for this and for the share app should be v2 as Android can be complex.
