### ISSUE TITLE
API Review: BeginInvokeOnMainThread

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Caboodle#119]
Discussion:

Should it be called BeginInvokeOnMainThread or InvokeOnMainThread

Via C# docs:

* Delegate.Invoke: Executes synchronously, on the same thread.
* Delegate.BeginInvoke: Executes asynchronously, on a threadpool thread.
* Control.Invoke: Executes on the UI thread, but calling thread waits for completion before continuing.
* Control.BeginInvoke: Executes on the UI thread, and calling thread doesn't wait for completion.

API Review to ensure we do what we say:
Today we are:

* Android: Post to looper
* iOS: calls BeginInvokeOnMainThread and calls (action.Invoke)
* uwp we run async on the dispatcher

**Comment by Redth** [comment]
**Android**
Post starts a Runnable and does not wait for its result (and we use the Main Thread looper), so our call returns immediately, not waiting for the actual code block to finish executing on the UI Thread.

**iOS:**
Similar to Android, we queue the NSAction to be executed on the main thread, and return back to the caller after it is queued.  Again, not waiting for the actual code block to finish executing.

**UWP:**
Schedules the provided callback on the UI thread from a worker thread, and returns the results asynchronously.  So, the results are something we could use to determine when the code block is done executing, but currently we are simply watching that op for an error, and not actually blocking on the caller for the code to execute.

**Summary**
I think BeginInvokeOnMainThread is an appropriate name.  In all cases we are merely queueing a code block to be executed on the main thread, and not actually waiting for the completion of the code block execution.  

Also, Xamarin.Forms uses this same naming, I'd assume for the same reasons.  

I think this naming is fine as is.
