### ISSUE TITLE
Browser API's

### ISSUE THREAD

**Issue by Redth** [xamarin/Caboodle#13]
Open links in browser (shell out to native, or use embedded system browser), with some customizability.

Some discussed points:
 - Only implement what most browsers support (no custom views, buttons, etc)
 - Colors are OK to implement
 - Android Support CustomTabs dependency is ok

**Comment by mattleibow** [comment]
When showing a link, we could have options like:

```csharp
class Options {
    BrowserType Type { get; }
}

enum BrowserType {
    // always shell out to the external app
    AlwaysUseExternalBrowser,

    // if the platform supports it, use an embedded browser:
    // safari view controller or chrome tabs
    PreferEmbeddedBrowser,
}
```

**Comment by jamesmontemagno** [comment]
I like that,not sure about the names of them, but I like it. Embedded sounds like we are hosting a webview a bit. The default should just be preferembeddedbrowser :)

Colors should be just like Xamarin.Forms if we can. Set and R/G/B/A or set a Hex string. We should create the System.Drawing.Color API here. 

The API should be simple: 

- Browser.Open(string url, Options options = null)
- Browser.Open(Url url, Options options = null)

**Comment by Redth** [comment]
Yeah agree on the embedded naming, maybe it should be something like `PreferInsideAppBrowser`?

Agree, this should be the default option too.

**Comment by jamesmontemagno** [comment]
Maybe PreferInternal, AlwaysUseExternal.

I don't think we need Browser in the name as it should be in the Enum name.

**Comment by Redth** [comment]
Is internal descriptive enough ?  Internal system? I suppose the docs can help describe

**Comment by jamesmontemagno** [comment]
Hmmm, i think it needs a better name

**Comment by moljac** [comment]
This nomenclature is confusing out of Xamarin ecosystem too.

In most cases

* embedded Browser (UIWebView, WebView, BrowserControl in UWP)

* external/system Browser == . Native UI

**Comment by moljac** [comment]
iOS - Do we want support for UIWebView and/or WKWebView? 
For embedded browser...
Vote pls.
@mattleibow  @Redth @jamesmontemagno (and everyone not mentioned)

**Comment by Redth** [comment]
I would say no. 

If you want a full page browser then SFSafariViewController / CustomTabs are the better way to go. Only real use case I'm aware of for using webviews anymore is to not show a full page browser which is something we aren't going to be able to support anyway (too much UI work)

**Comment by mattleibow** [comment]
I also vote that there be no embedded `UIWebView` as this is a very UI-y thing and Caboodle is not meant for that. If you want an embedded web view, use Xamarin.Forms and add a `<WebView>`.

**Comment by jamesmontemagno** [comment]
So, we would fall back to just OpenUrl:

iOS:
```

if(AlwaysUseExternal)
{
   UIApplication.SharedApplication.OpenUrl(new NSUrl(url));
}
else
{
var sfViewController = new SFSafariViewController(new NSUrl(url), options?.UseSafariReaderMode ?? false);
//set colors here, we can set tintcolors on iOS 10+
var vc = GetVisibleViewController();

 if (sfViewController.PopoverPresentationController != null)
{
   sfViewController.PopoverPresentationController.SourceView = vc.View;
}
                    
await vc.PresentViewControllerAsync(sfViewController, true);
}
```

Android:
```
if(AlwaysUseExternal)
{
  var intent = new Intent(Intent.ActionView);
                    intent.SetData(Android.Net.Uri.Parse(url));

                    intent.SetFlags(ActivityFlags.ClearTop);
                    intent.SetFlags(ActivityFlags.NewTask);
                    Application.Context.StartActivity(intent);
}
else
{
 var tabsBuilder = new CustomTabsIntent.Builder();
                    tabsBuilder.SetShowTitle(options?.ChromeShowTitle ?? false);

                    var toolbarColor = options?.ChromeToolbarColor;
                    if (toolbarColor != null)
                        tabsBuilder.SetToolbarColor(toolbarColor.ToNativeColor());

                    var intent = tabsBuilder.Build();
                    intent.LaunchUrl(.Activity, Android.Net.Uri.Parse(url));
//chrome custom tabs will fall back to normal launching of browser if they don't exist
}

```

UWP:
```
await Windows.System.Launcher.LaunchUriAsync(new Uri(url));
```

**Comment by mattleibow** [comment]
We could do something like this:

```csharp
static class Browser {
    // don't use system and use default colors
    static void Open() => Open(false);

    // always use system browser
    static void Open(bool useSystemBrowser); 

    // try use tabs with colors, otherwise fail over to default browser
    static void Open(Options options);
}
```
