### ISSUE TITLE
mdoc Documentation

### ISSUE THREAD

**Issue by Redth** [xamarin/Caboodle#16]
We want to document our API's with mdoc, and from that generate msxml docs to ship in the nupkg for providing intelligence information.

**Comment by mattleibow** [comment]
How are we going to add the XML from mdoc into the .nupkg?

Right now we are using the Msbuild `<GenerateDocumentationFile>` element to auto-create the docs and add it to the package with `<GeneratePackageOnBuild>`. If we use mdoc, then we can't do this.

**Comment by Redth** [comment]
CI is still using `/t:Pack` to get the nupkg.... So what needs to happen to use the xml docs generated from the mdoc to do this?

**Comment by mattleibow** [comment]
Closing this as mdoc tooling has been merged in: #5
