### ISSUE TITLE
Battery API's

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Caboodle#20]
Simple battery % and charging state.

```csharp
class Battery {
    // range from [0.0, 1.0]
    // -1 is unknown or invalid
    double ChargeLevel { get; }

    BatteryState State { get; }

    event EventHandler<BatteryChangedEventArgs> BatteryChanged;
}
```

```csharp
class BatteryChangedEventArgs : EventArgs {
    ctor(double level, BatteryStatus status);

    double ChargeLevel { get; }
    BatteryState State { get; }
}
```

```csharp
enum BatteryState {
    Unknown,
    Charging,
    Discharging,
    Full,
    NotCharging
}
```

Native platform features:

| Platform | State                                             |
| -------- | ------------------------------------------------- |
| iOS      | unknown, unplugged, charging, full                |
| Android  | charging, discharging, full, notCharging, unknown |
| UWP      | charging, discharging, idle, notPresent           |

iOS Notes: 
 - `Discharging` can be mapped from `unplugged`.
 - `NotCharging` can be ignored.

UWP Notes:
 - `NotCharging` can be mapped from `idle`.
 - `Full` can be mapped if `ChargeLevel >= 100`.
 - `Unknown` can be mapped if `ChargeLevel <= 0 || notPresent`

**Comment by mattleibow** [comment]
based on https://github.com/jamesmontemagno/BatteryPlugin

**Comment by Redth** [comment]
I'm liking this

**Comment by jamesmontemagno** [comment]
Absolutely perfect! <3
2 questions:
How about PowerSource?

Additionally:
Should we have a batterystatechanged event or a power source changed?

My assumption is that these can be static too....
