### ISSUE TITLE
Share API

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Caboodle#22]
Ability to Share text via a share sheet.

Things to consider:

- Title
- Chooser Title
- Message
- Link
- Activities to Exclude on iOS?

Each of these work a bit different so we should look at this.

**Comment by mattleibow** [comment]
I remember a discussion with someone on this. It appears that the activities on iOS are really things that are grouped by what the content type is. For example, when sharing text, we would want Facebook or Mail, but not Vimeo or Camera Roll. The same might be said for a picture, we want Facebook and Camera Roll, but not Vimeo or iBooks.

We might be able to hide the concept of iOS's activities behind a "content type" indicator.
