### ISSUE TITLE
SMS API's

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Caboodle#26]
A simple API to send an SMS.

```csharp
static class Sms {
    // whether or not the device can open a compose dialog
    static bool IsComposeSupported { get; }

    // whether or not the device can send in the background
    static bool IsSendSupported { get; }

    // open the compose window, throw if not supported
    static Task ComposeAsync(SmsMessage message);

    // send a message in the background, throw if not supported
    // this is supported only on Android and UWP
    static Task SendAsync(SmsMessage message);
}

class SmsMessage {
    SmsMessage(string body, string recipient);

    string Body { get; set; }
    string Recipient { get; set; }
}
```

For the discussion around exceptions, see #19

**Comment by F1nZeR** [comment]
What about Multi-SIM card support? It is pretty common situation on Android platform. 
Should it be supported as a separate prop on droid side?

**Comment by Geertvdc** [comment]
Hi @jamesmontemagno i'll try to see if i can implement this since it is up for grabs

**Comment by jamesmontemagno** [comment]
I believe there is a pr

**Comment by jamesmontemagno** [comment]
I believe there is a pr

**Comment by Geertvdc** [comment]
oh yeah now i see. might wanna move the "up for grabs" then cause i thought i could pick this one up

**Comment by mattleibow** [comment]
After some more discussion (which is always good) we have decided to try another approach - copying the style of emails: https://github.com/xamarin/Caboodle/issues/27

**Comment by jamesmontemagno** [comment]
Looks perfect. Should it be "body" or "message", should be consistent.

**Comment by mattleibow** [comment]
I used "body" as the type is the message. This is what email does.
I was thinking `var message = new SmsMessage()` and then `message.Message` is a bit weird.

**Comment by jamesmontemagno** [comment]
ahhhh, yeah makes sense. I think the method's properties should match :)

**Comment by jamesmontemagno** [comment]
oh wait
nm. ignore me
