### ISSUE TITLE
Should Preferences support Nullable<T>?

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Caboodle#45]
This may be something that will be very useful.

@jamesmontemagno has done this in his plugin: https://github.com/jamesmontemagno/SettingsPlugin/blob/master/src/Plugin.Settings.Android/Settings.cs#L53-L60

**Comment by Redth** [comment]
We had talked about not supported null values and the user just using `Remove`...

**Comment by mattleibow** [comment]
We could support an overload that takes the nullable to make life easier:

```csharp
Set(string key, int? value) {
    if (value.HasValue)
        Set(key, value.Value);
    else
        Remove(key);
}

Set(string key, int value);
```

This way a dev doesn't have to always check before.

**Comment by Redth** [comment]
Let's wait for feedback from users to see if this is a common ask.  I'm hesitant to make setting null equate to remove implicitly.

**Comment by Brosten** [comment]
Where can I vote for this feature?

**Comment by mattleibow** [comment]
You can open new issue and maybe suggest why setting null is better than removing. Not trying to be funny or anything. I think we don't see the value yet?
So a new issue and let's start this again if you feel it is useful.
