### ISSUE TITLE
UI/Main Thread Invoke API

### ISSUE THREAD

**Issue by moljac** [xamarin/Caboodle#57]
UIThreadRunInvoker class offers unified API for calling methods on Main/UI thread from background threads (async methods).

```
UIThreadRunInvoker.BeginOnUIThread(Action action);
```
calls:

*   on Android

```
Platform.CurrentActivity(Action action);
```

*   on iOS

```
UIKit.UIAPplication.SharedApplication.BeginInvokeOnMainThread(Action action);
```

To investigate is call to `CoreFoundation.DispatchQueue.MainQueue.DispatchAsync(Action)`

*    on UWP

```
Windows.ApplicationModel.Core.CoreAPplication.MainView.CoreWindow.Dispatcher.RunAsync(Action)
```

Next steps (if API survives) is to add overloads for `Func<>` arguments/parameters...

**Comment by Redth** [comment]
If we add this sort of API I think it should maybe go in Platform rather than a new separate class.

**Comment by moljac** [comment]
I'm OK with every outcome. I thought it might go into Platform, but I did not want to break initial design, so I added it as is - in a separate class (only change is static API). If API is OK, refactoring (moving) will be easy.

I have no strong opinion. It is up to design (and decision makers) to decide. Again if this API gets added. It saved me time on other projects by allowing me not to remeber/lookup exact platform API.

**Comment by Redth** [comment]
#49 appears to include something on this already.

**Comment by jamesmontemagno** [comment]
Yeah, I think #49 does it best as it is based off of Xamarin.Forms and it should be in Platform.

I recommend we pull in Battery and then use this API.

**Comment by Redth** [comment]
This is taken care of by #49
