### ISSUE TITLE
PRs accepted?

### ISSUE THREAD

**Issue by alanag13** [xamarin/Caboodle#63]
I see that keystore/keychain is planned -- I have an implementation of this done for iOS/Android, and I don't think it would take much effort to add UWP. Wasn't sure how far along on that you were or if perhaps this feature was meant for something larger (like Xamarin.Auth), but if you're just looking for the basic keystore/keychain implementation im happy to send a PR :-)

**Comment by moljac** [comment]
@alanag13 

It is mostly done. I have Android and iOS bits too and am comparing with the code from Xamarin.Auth (AccountStore), just to check we haven't forgtten something. UWP implementation is mostly done too. 

I will push it soon and any comments regarding security aspects is welcome. (We are actually waiting for security gurus to check the code).

**Comment by alanag13** [comment]
Can't say I'm one of those, haha. Any other items I could contribute too? Just thought it might be cool to get in on this while it's young. Are the other issues that you guys have filed "fair game"?

**Comment by jamesmontemagno** [comment]
We will be marking issues as "up-for-grabs" when ready.

**Comment by jamesmontemagno** [comment]
Updated readme with information and a few for up for grabs.

**Comment by alanag13** [comment]
excellent, thanks!
