### ISSUE TITLE
Storage Secure API

### ISSUE THREAD

**Issue by moljac** [xamarin/Caboodle#66]
Storage Secure (Secured) API

| Platform                           | Implementation                                         |
|------------------------|------------------------------------------|
| Android                          | KeyStore                                                      |
| iOS                                  | KeyChain                                                     |
| UWP                               |  StorageFile + DataProtectionProvider      |

1.   `Task<string> LoadAsync(string filename)`
2.  `Task SaveAsync(string filename, string content)`

**Comment by moljac** [comment]
Branch:
https://github.com/xamarin/Caboodle/tree/master_based_storagesecure

**Comment by mattleibow** [comment]
A diff: https://github.com/xamarin/Caboodle/compare/master_based_storagesecure
