### ISSUE TITLE
Flashlight API

### ISSUE THREAD

**Issue by moljac** [xamarin/Caboodle#70]
# Description

API for turning on and off Flashlight

# API

```csharp
static class Flashlight
{
    static void On();
    static void Off();

    static FlashlightState State { get; }
}
```

```csharp
enum FlashlightState
{
    Unknown,
    On,
    Off
}
```

**Comment by Redth** [comment]
We'll need to check for permissions properly on each platform and request them / throw exceptions when they are denied.

Do we need `async Task` here at all for the on/off methods?

**Comment by ravinderjangra** [comment]
Is someone working on it internally?

**Comment by jamesmontemagno** [comment]
Issues are marked as "up for grabs" if they are open for community contributions.
