### ISSUE TITLE
Connectivity API's

### ISSUE THREAD

**Issue by Redth** [xamarin/Caboodle#8]
A really simple way to check if we have an internet connection.

## Connectivity
**Properties**
- *bool* **IsConnected** (readonly)
- *IEnumerable<ConnectionType>* **ConnectionTypes** (readonly)

**Events**
- *EventHandler<ConnectivityChangedEventArgs>* **ConnectivityChanged**
- *EventHandler<ConnectivityTypeChangedEventArgs>* **ConnectivityTypeChanged**

## ConnectionType (enum)
- Cellular
- WiFi
- Desktop
- Wimax
- Other
- Bluetooth

## ConnectivityChangedEventArgs : EventArgs
**Constructors**
- **ConnectivityChangedEventArgs** (*bool* isConnected)

**Properties**
- *bool* **IsConnected** (readonly)
## ConnectivityTypeChangedEventArgs : ConnectivityChangedEventArgs

**Constructors**
- **ConnectivityTypeChangedEventArgs** (*bool* isConnected, *IEnumerable<ConnectionType>* types)

**Properties**
- *IEnumerable<ConnectionType>* **ConnectionTypes** (readonly)

**Comment by jamesmontemagno** [comment]
Proposing we return an enum for IsConnected and change it to "NetworkAccess"

```
NetworkAccess NetworkAccess {get;}

enum NetworkAccess
{
    ConstrainedInternet,
    Internet,
    Local,
    None,
    Unknown 
}
```

Comes from: https://docs.microsoft.com/en-us/uwp/api/windows.networking.connectivity.networkconnectivitylevel

**Comment by jamesmontemagno** [comment]
Also, maybe we should change "ConnectionTypes" to "ActiveProfiles"?

https://docs.microsoft.com/en-us/uwp/api/windows.networking.connectivity.connectionprofile

**Comment by jamesmontemagno** [comment]
Android is a bit tricky... really need to validate https://developer.android.com/reference/android/net/NetworkCapabilities.html

**Comment by jamesmontemagno** [comment]
Is connected on Android is a bit tricky as I have seen from my plugins. Google documents: https://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html and in fact they use this code in the I/O app from last year. My  code that I have written previously is more based on looping through active network adapters.
