### ISSUE TITLE
Device Info API's

### ISSUE THREAD

**Issue by Redth** [xamarin/Caboodle#9]
Basic information about a Device and its Operating system.

## DeviceInfo
**Properties**
- *string* **Model** (readonly)
- *string* **Manufacturer** (readonly)
- *string* **DeviceName** (readonly)
- *string* **Version** (readonly)
- *Version* **VersionNumber** (readonly)
- *string* **AppVersion** (readonly)
- *string* **AppBuild** (readonly)
- *string* **Platform** (readonly)
  > These values returned will match those which Xamarin.Forms uses.
- *string* **Idiom** (readonly)
- *bool* **IsDevice** (readonly)

## DeviceInfo.Idioms
**Consts**
- string Car = nameof (Car)
- string Desktop = *nameof (Desktop)*
- string Phone = *nameof (Phone)*
- string Tablet = *nameof (Tablet)*
- string Television = *nameof (Television)*
- string Watch = *nameof (Watch)*

## DeviceInfo.Platforms
**Consts**
- *string* **Android** = *nameof (**Android**)*
- *string* **iOS** = *nameof (iOS)*
- *string* **UWP** = *“Windows”* // must match Forms

**Comment by Redth** [comment]
I think battery information should exist somewhere in here too, perhaps something like:

## Battery
**Methods**
- *static double* **Percent** (readonly)

**Comment by mattleibow** [comment]
Maybe battery needs to be a separate API. It may be useful to have more properties:

 - **Percent**
 - **IsCharging** or **ChargingState**

**Comment by mattleibow** [comment]
The DeviceInfo API probably should either be static or have a private constructor.

**Comment by Redth** [comment]
Yes battery goes in its own class. 

Can we get charging state on each platform?

**Comment by mattleibow** [comment]
I think so. Moved to https://github.com/xamarin/Caboodle/issues/20

**Comment by jamesmontemagno** [comment]
Additional APIs:
* IsEmulator
* DeviceWidth
* DeviceHeight
* DeviceOrientation

**Comment by jamesmontemagno** [comment]
We should evaluate what Id means as well. Is it the serial number or a specific Id. I struggled with this a lot.

**Comment by Redth** [comment]
I think SerialNumber should give that info and Id should be a unique id compliant with the platform.

**Comment by mattleibow** [comment]
Removing the `DeviceInfo.Id` property as this requires more research.
See #61.

**Comment by mattleibow** [comment]
Merged in #54
