### ISSUE TITLE
Move Application info into "AppInfo" class

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Caboodle#95]
### Description
Right now we have DeviceInfo, which also holds a bunch of information about the Application too.

This way we can have:

AppInfo.Version and DeviceInfo.Version :)

Would be really nice.

**Comment by mattleibow** [comment]
I think this is a good one.

**Comment by mattleibow** [comment]
Changes made in 1e4ae52d285902e529749c11e68402d0b2511869
